// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/mall_server/proto.proto

package mall_server

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Sku struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cover                string   `protobuf:"bytes,3,opt,name=cover,proto3" json:"cover,omitempty"`
	GoodsId              int64    `protobuf:"varint,4,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Price                int64    `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Inventory            int64    `protobuf:"varint,6,opt,name=inventory,proto3" json:"inventory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sku) Reset()         { *m = Sku{} }
func (m *Sku) String() string { return proto.CompactTextString(m) }
func (*Sku) ProtoMessage()    {}
func (*Sku) Descriptor() ([]byte, []int) {
	return fileDescriptor_69fa3d7341960854, []int{0}
}

func (m *Sku) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sku.Unmarshal(m, b)
}
func (m *Sku) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sku.Marshal(b, m, deterministic)
}
func (m *Sku) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sku.Merge(m, src)
}
func (m *Sku) XXX_Size() int {
	return xxx_messageInfo_Sku.Size(m)
}
func (m *Sku) XXX_DiscardUnknown() {
	xxx_messageInfo_Sku.DiscardUnknown(m)
}

var xxx_messageInfo_Sku proto.InternalMessageInfo

func (m *Sku) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Sku) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Sku) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *Sku) GetGoodsId() int64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *Sku) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Sku) GetInventory() int64 {
	if m != nil {
		return m.Inventory
	}
	return 0
}

type GetGoodsDetailReq struct {
	GoodsId              int64    `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGoodsDetailReq) Reset()         { *m = GetGoodsDetailReq{} }
func (m *GetGoodsDetailReq) String() string { return proto.CompactTextString(m) }
func (*GetGoodsDetailReq) ProtoMessage()    {}
func (*GetGoodsDetailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_69fa3d7341960854, []int{1}
}

func (m *GetGoodsDetailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoodsDetailReq.Unmarshal(m, b)
}
func (m *GetGoodsDetailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoodsDetailReq.Marshal(b, m, deterministic)
}
func (m *GetGoodsDetailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoodsDetailReq.Merge(m, src)
}
func (m *GetGoodsDetailReq) XXX_Size() int {
	return xxx_messageInfo_GetGoodsDetailReq.Size(m)
}
func (m *GetGoodsDetailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoodsDetailReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoodsDetailReq proto.InternalMessageInfo

func (m *GetGoodsDetailReq) GetGoodsId() int64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

type GetGoodsDetailRes struct {
	GoodsId              int64    `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Images               string   `protobuf:"bytes,3,opt,name=images,proto3" json:"images,omitempty"`
	Status               int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Skus                 []*Sku   `protobuf:"bytes,5,rep,name=skus,proto3" json:"skus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetGoodsDetailRes) Reset()         { *m = GetGoodsDetailRes{} }
func (m *GetGoodsDetailRes) String() string { return proto.CompactTextString(m) }
func (*GetGoodsDetailRes) ProtoMessage()    {}
func (*GetGoodsDetailRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_69fa3d7341960854, []int{2}
}

func (m *GetGoodsDetailRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoodsDetailRes.Unmarshal(m, b)
}
func (m *GetGoodsDetailRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoodsDetailRes.Marshal(b, m, deterministic)
}
func (m *GetGoodsDetailRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoodsDetailRes.Merge(m, src)
}
func (m *GetGoodsDetailRes) XXX_Size() int {
	return xxx_messageInfo_GetGoodsDetailRes.Size(m)
}
func (m *GetGoodsDetailRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoodsDetailRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoodsDetailRes proto.InternalMessageInfo

func (m *GetGoodsDetailRes) GetGoodsId() int64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *GetGoodsDetailRes) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetGoodsDetailRes) GetImages() string {
	if m != nil {
		return m.Images
	}
	return ""
}

func (m *GetGoodsDetailRes) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *GetGoodsDetailRes) GetSkus() []*Sku {
	if m != nil {
		return m.Skus
	}
	return nil
}

type CreateOrderReq struct {
	GoodsId              int64    `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	SkuId                int64    `protobuf:"varint,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	BuyNum               int64    `protobuf:"varint,3,opt,name=buy_num,json=buyNum,proto3" json:"buy_num,omitempty"`
	Uid                  int64    `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Phone                string   `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Province             string   `protobuf:"bytes,7,opt,name=province,proto3" json:"province,omitempty"`
	City                 string   `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	Region               string   `protobuf:"bytes,9,opt,name=region,proto3" json:"region,omitempty"`
	Addr                 string   `protobuf:"bytes,10,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderReq) Reset()         { *m = CreateOrderReq{} }
func (m *CreateOrderReq) String() string { return proto.CompactTextString(m) }
func (*CreateOrderReq) ProtoMessage()    {}
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_69fa3d7341960854, []int{3}
}

func (m *CreateOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderReq.Unmarshal(m, b)
}
func (m *CreateOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderReq.Marshal(b, m, deterministic)
}
func (m *CreateOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderReq.Merge(m, src)
}
func (m *CreateOrderReq) XXX_Size() int {
	return xxx_messageInfo_CreateOrderReq.Size(m)
}
func (m *CreateOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderReq proto.InternalMessageInfo

func (m *CreateOrderReq) GetGoodsId() int64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *CreateOrderReq) GetSkuId() int64 {
	if m != nil {
		return m.SkuId
	}
	return 0
}

func (m *CreateOrderReq) GetBuyNum() int64 {
	if m != nil {
		return m.BuyNum
	}
	return 0
}

func (m *CreateOrderReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CreateOrderReq) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *CreateOrderReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateOrderReq) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *CreateOrderReq) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CreateOrderReq) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *CreateOrderReq) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type CreateOrderRes struct {
	OrderCode            string   `protobuf:"bytes,1,opt,name=order_code,json=orderCode,proto3" json:"order_code,omitempty"`
	GoodsName            string   `protobuf:"bytes,2,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	SkuName              string   `protobuf:"bytes,3,opt,name=sku_name,json=skuName,proto3" json:"sku_name,omitempty"`
	Price                int64    `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRes) Reset()         { *m = CreateOrderRes{} }
func (m *CreateOrderRes) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRes) ProtoMessage()    {}
func (*CreateOrderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_69fa3d7341960854, []int{4}
}

func (m *CreateOrderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRes.Unmarshal(m, b)
}
func (m *CreateOrderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRes.Marshal(b, m, deterministic)
}
func (m *CreateOrderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRes.Merge(m, src)
}
func (m *CreateOrderRes) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRes.Size(m)
}
func (m *CreateOrderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRes proto.InternalMessageInfo

func (m *CreateOrderRes) GetOrderCode() string {
	if m != nil {
		return m.OrderCode
	}
	return ""
}

func (m *CreateOrderRes) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

func (m *CreateOrderRes) GetSkuName() string {
	if m != nil {
		return m.SkuName
	}
	return ""
}

func (m *CreateOrderRes) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type AutoCloseOrderReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoCloseOrderReq) Reset()         { *m = AutoCloseOrderReq{} }
func (m *AutoCloseOrderReq) String() string { return proto.CompactTextString(m) }
func (*AutoCloseOrderReq) ProtoMessage()    {}
func (*AutoCloseOrderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_69fa3d7341960854, []int{5}
}

func (m *AutoCloseOrderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoCloseOrderReq.Unmarshal(m, b)
}
func (m *AutoCloseOrderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoCloseOrderReq.Marshal(b, m, deterministic)
}
func (m *AutoCloseOrderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoCloseOrderReq.Merge(m, src)
}
func (m *AutoCloseOrderReq) XXX_Size() int {
	return xxx_messageInfo_AutoCloseOrderReq.Size(m)
}
func (m *AutoCloseOrderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoCloseOrderReq.DiscardUnknown(m)
}

var xxx_messageInfo_AutoCloseOrderReq proto.InternalMessageInfo

type AutoCloseOrderRes struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoCloseOrderRes) Reset()         { *m = AutoCloseOrderRes{} }
func (m *AutoCloseOrderRes) String() string { return proto.CompactTextString(m) }
func (*AutoCloseOrderRes) ProtoMessage()    {}
func (*AutoCloseOrderRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_69fa3d7341960854, []int{6}
}

func (m *AutoCloseOrderRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoCloseOrderRes.Unmarshal(m, b)
}
func (m *AutoCloseOrderRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoCloseOrderRes.Marshal(b, m, deterministic)
}
func (m *AutoCloseOrderRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoCloseOrderRes.Merge(m, src)
}
func (m *AutoCloseOrderRes) XXX_Size() int {
	return xxx_messageInfo_AutoCloseOrderRes.Size(m)
}
func (m *AutoCloseOrderRes) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoCloseOrderRes.DiscardUnknown(m)
}

var xxx_messageInfo_AutoCloseOrderRes proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Sku)(nil), "sku")
	proto.RegisterType((*GetGoodsDetailReq)(nil), "get_goods_detail_req")
	proto.RegisterType((*GetGoodsDetailRes)(nil), "get_goods_detail_res")
	proto.RegisterType((*CreateOrderReq)(nil), "create_order_req")
	proto.RegisterType((*CreateOrderRes)(nil), "create_order_res")
	proto.RegisterType((*AutoCloseOrderReq)(nil), "auto_close_order_req")
	proto.RegisterType((*AutoCloseOrderRes)(nil), "auto_close_order_res")
}

func init() { proto.RegisterFile("api/mall_server/proto.proto", fileDescriptor_69fa3d7341960854) }

var fileDescriptor_69fa3d7341960854 = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0xdd, 0x34, 0x69, 0xda, 0xcc, 0x02, 0x2a, 0x56, 0xbb, 0x78, 0x0b, 0x48, 0x55, 0x4e, 0x3d,
	0x65, 0xc5, 0x22, 0xf1, 0x01, 0xe5, 0xb4, 0x97, 0x1e, 0x72, 0xe4, 0x12, 0xa5, 0xb1, 0x55, 0xac,
	0x34, 0x71, 0xf1, 0xd8, 0x95, 0x7a, 0xe4, 0x07, 0xe0, 0xaf, 0xf8, 0x23, 0xee, 0xc8, 0x76, 0x55,
	0xb2, 0xdd, 0xc0, 0x5e, 0xa2, 0x79, 0x6f, 0x66, 0x62, 0xbf, 0xe7, 0x19, 0x78, 0x5b, 0xee, 0xc5,
	0x5d, 0x53, 0xee, 0x76, 0x05, 0x72, 0x75, 0xe0, 0xea, 0x6e, 0xaf, 0xa4, 0x96, 0x99, 0xfb, 0xa6,
	0x3f, 0x02, 0x08, 0xb1, 0x36, 0xe4, 0x15, 0x0c, 0x04, 0xa3, 0xc1, 0x22, 0x58, 0x86, 0xf9, 0x40,
	0x30, 0x42, 0x20, 0x6a, 0xcb, 0x86, 0xd3, 0xc1, 0x22, 0x58, 0x26, 0xb9, 0x8b, 0xc9, 0x14, 0x86,
	0x95, 0x3c, 0x70, 0x45, 0x43, 0x47, 0x7a, 0x40, 0x6e, 0x61, 0xbc, 0x95, 0x92, 0x61, 0x21, 0x18,
	0x8d, 0x5c, 0xff, 0xc8, 0xe1, 0x07, 0x66, 0x1b, 0xf6, 0x4a, 0x54, 0x9c, 0x0e, 0x1d, 0xef, 0x01,
	0x79, 0x07, 0x89, 0x68, 0x0f, 0xbc, 0xd5, 0x52, 0x1d, 0x69, 0xec, 0x32, 0x7f, 0x89, 0xf4, 0x03,
	0x4c, 0xb7, 0x5c, 0x17, 0xfe, 0x97, 0x8c, 0xeb, 0x52, 0xec, 0x0a, 0xc5, 0xbf, 0x3d, 0x3a, 0x26,
	0x78, 0x74, 0x4c, 0xfa, 0x33, 0xe8, 0xed, 0xc1, 0xff, 0xf4, 0xf4, 0xea, 0xbb, 0x81, 0x58, 0x34,
	0xe5, 0x96, 0xe3, 0x49, 0xe0, 0x09, 0x59, 0x1e, 0x75, 0xa9, 0x0d, 0x3a, 0x7d, 0xc3, 0xfc, 0x84,
	0x08, 0x85, 0x08, 0x6b, 0x83, 0x74, 0xb8, 0x08, 0x97, 0xd7, 0xf7, 0x51, 0x86, 0xb5, 0xc9, 0x1d,
	0x93, 0xfe, 0x0e, 0x60, 0x52, 0x29, 0x5e, 0x6a, 0x5e, 0x48, 0xc5, 0xb8, 0x7a, 0x46, 0x01, 0x99,
	0x41, 0x8c, 0xb5, 0xb1, 0x89, 0x81, 0x77, 0x0a, 0x6b, 0xf3, 0xc0, 0xc8, 0x1b, 0x18, 0x6d, 0xcc,
	0xb1, 0x68, 0x4d, 0xe3, 0x6e, 0x14, 0xe6, 0xf1, 0xc6, 0x1c, 0xd7, 0xa6, 0x21, 0x13, 0x08, 0xcd,
	0xd9, 0x6e, 0x1b, 0x3a, 0xab, 0xbf, 0xca, 0xd6, 0x5b, 0x9d, 0xe4, 0x1e, 0x9c, 0x55, 0xc6, 0x1d,
	0x95, 0x73, 0x18, 0xef, 0x95, 0x3c, 0x88, 0xb6, 0xe2, 0x74, 0xe4, 0xf8, 0x33, 0xb6, 0xf5, 0x95,
	0xd0, 0x47, 0x3a, 0xf6, 0xf5, 0x36, 0xb6, 0xea, 0x15, 0xdf, 0x0a, 0xd9, 0xd2, 0xc4, 0xbb, 0xe2,
	0x91, 0xad, 0x2d, 0x19, 0x53, 0x14, 0x7c, 0xad, 0x8d, 0xd3, 0xef, 0x4f, 0x75, 0x23, 0x79, 0x0f,
	0xe0, 0x41, 0x25, 0x19, 0x77, 0xca, 0x93, 0x3c, 0x71, 0xcc, 0x67, 0xc9, 0xb8, 0x4d, 0x7b, 0x5b,
	0x3a, 0xef, 0x91, 0x38, 0x66, 0x6d, 0xaf, 0x7b, 0x0b, 0x63, 0x6b, 0x8d, 0x4b, 0xfa, 0x67, 0x19,
	0x61, 0x6d, 0xd6, 0xa7, 0x79, 0xf4, 0xe3, 0x15, 0x75, 0xc6, 0x2b, 0xbd, 0x81, 0x69, 0x69, 0xb4,
	0x2c, 0xaa, 0x9d, 0xc4, 0x8e, 0xfd, 0xff, 0xe0, 0xf1, 0xfe, 0x57, 0x00, 0x91, 0xdd, 0x0e, 0xb2,
	0x82, 0xc9, 0xe5, 0x14, 0x91, 0x59, 0xd6, 0x37, 0x8c, 0xf3, 0x5e, 0x1a, 0xd3, 0x2b, 0xf2, 0x09,
	0x5e, 0x74, 0xf5, 0x93, 0xd7, 0xd9, 0xe5, 0x18, 0xcc, 0x9f, 0x50, 0xb6, 0x6f, 0x05, 0x93, 0xcb,
	0xcb, 0x91, 0x59, 0xd6, 0xa7, 0x63, 0xde, 0x4b, 0x63, 0x7a, 0xb5, 0x7a, 0xf9, 0xe5, 0xba, 0xb3,
	0xe5, 0x9b, 0xd8, 0x2d, 0xf8, 0xc7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x26, 0xc6, 0x82, 0xbb,
	0xff, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MallClient is the client API for Mall service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MallClient interface {
	GetGoodsDetail(ctx context.Context, in *GetGoodsDetailReq, opts ...grpc.CallOption) (*GetGoodsDetailRes, error)
	CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderRes, error)
	AutoCloseOrder(ctx context.Context, in *AutoCloseOrderReq, opts ...grpc.CallOption) (*AutoCloseOrderRes, error)
}

type mallClient struct {
	cc *grpc.ClientConn
}

func NewMallClient(cc *grpc.ClientConn) MallClient {
	return &mallClient{cc}
}

func (c *mallClient) GetGoodsDetail(ctx context.Context, in *GetGoodsDetailReq, opts ...grpc.CallOption) (*GetGoodsDetailRes, error) {
	out := new(GetGoodsDetailRes)
	err := c.cc.Invoke(ctx, "/mall/get_goods_detail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallClient) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderRes, error) {
	out := new(CreateOrderRes)
	err := c.cc.Invoke(ctx, "/mall/create_order", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mallClient) AutoCloseOrder(ctx context.Context, in *AutoCloseOrderReq, opts ...grpc.CallOption) (*AutoCloseOrderRes, error) {
	out := new(AutoCloseOrderRes)
	err := c.cc.Invoke(ctx, "/mall/auto_close_order", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MallServer is the server API for Mall service.
type MallServer interface {
	GetGoodsDetail(context.Context, *GetGoodsDetailReq) (*GetGoodsDetailRes, error)
	CreateOrder(context.Context, *CreateOrderReq) (*CreateOrderRes, error)
	AutoCloseOrder(context.Context, *AutoCloseOrderReq) (*AutoCloseOrderRes, error)
}

// UnimplementedMallServer can be embedded to have forward compatible implementations.
type UnimplementedMallServer struct {
}

func (*UnimplementedMallServer) GetGoodsDetail(ctx context.Context, req *GetGoodsDetailReq) (*GetGoodsDetailRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoodsDetail not implemented")
}
func (*UnimplementedMallServer) CreateOrder(ctx context.Context, req *CreateOrderReq) (*CreateOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (*UnimplementedMallServer) AutoCloseOrder(ctx context.Context, req *AutoCloseOrderReq) (*AutoCloseOrderRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AutoCloseOrder not implemented")
}

func RegisterMallServer(s *grpc.Server, srv MallServer) {
	s.RegisterService(&_Mall_serviceDesc, srv)
}

func _Mall_GetGoodsDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoodsDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallServer).GetGoodsDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mall/GetGoodsDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallServer).GetGoodsDetail(ctx, req.(*GetGoodsDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mall_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mall/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallServer).CreateOrder(ctx, req.(*CreateOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mall_AutoCloseOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoCloseOrderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MallServer).AutoCloseOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mall/AutoCloseOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MallServer).AutoCloseOrder(ctx, req.(*AutoCloseOrderReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mall_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mall",
	HandlerType: (*MallServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get_goods_detail",
			Handler:    _Mall_GetGoodsDetail_Handler,
		},
		{
			MethodName: "create_order",
			Handler:    _Mall_CreateOrder_Handler,
		},
		{
			MethodName: "auto_close_order",
			Handler:    _Mall_AutoCloseOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/mall_server/proto.proto",
}
